name: Master

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Deno
        uses: denolib/setup-deno@v2

      # See comment in "Run Unit Tests" job.
      # - name: Install Rhum
      #   run: deno install -Af https://raw.githubusercontent.com/drashland/rhum/rhum-cli/cli.ts

      - name: Run Unit Tests
        # TODO (crookse) When Rhum v2.0 is released, this step will need to be updated from using
        # `rhum-cli` to `rhum`. The reason it's `rhum-cli` right now is because the branch name
        # is `rhum-cli` (as seen in the above step).
        run: |
          export PATH="~/.deno/bin:$PATH"
          deno test -A tests

  linter:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Deno v${{ matrix.deno }}
        uses: denolib/setup-deno@master

      - name: Formatter
        run: deno fmt --check

      - name: Linter
        run: deno lint --ignore=tests/data
